import { useState } from 'react';
import './FAQ.css';

const FAQS = [
  { q: 'Do I own the blogs generated by Blogy?', a: 'Yes. All blogs created and published using Blogy belong entirely to you and stay on your website.' },
  { q: "Will the 'Blogy' content be SEO-friendly?", a: 'Yes, our content is fully optimized for SEO. Each article includes SEO-optimized titles, meta descriptions, and naturally placed keywords throughout the content. We ensure proper heading structure (H2, H3) and maintain a minimum length of 1,200–1,700 words for comprehensive coverage.' },
  { q: 'What happens after I use the free blogs?', a: 'You can upgrade to a paid plan to generate more blogs and remove Blogy branding—no content is deleted.' },
  { q: 'Which platforms does Blogy support?', a: 'Blogy works with Shopify, WebFlow, WordPress, Wix, and Custom Websites through simple integrations.' },
  { q: 'How is Blogy different from ChatGPT?', a: "Unlike ChatGPT, Blogy publishes the content to your website automatically. Blogy also crawls your website to analyze its structure, content, and internal linking. Our models are fine-tuned with up-to-date SEO data and competitor analysis, which ChatGPT doesn't have." },
  { q: 'Can I cancel my subscription anytime?', a: 'Absolutely. There are no long-term contracts, and you can cancel or change plans at any time.' },
  { q: 'Will Blogy integrate new SaaS in the future?', a: 'Yes. We ship new integrations on a regular cadence based on what teams ask for. Customer demand helps set our roadmap.' },
  { q: 'Does Blogy have a free plan?', a: 'Yes. Blogy offers a free forever plan so you can try core publishing features at no cost. Upgrade when you need higher limits, more automation, or premium options.' },
];

function FAQItem({ q, a }) {
  const [open, setOpen] = useState(false);
  return (
    <div className={`faq-item ${open ? 'open' : ''}`}>
      <button className="faq-q" onClick={() => setOpen(!open)} aria-expanded={open}>
        <span>{q}</span>
        <span className="faq-icon">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            {open ? <path d="M5 12h14"/> : <><path d="M12 5v14"/><path d="M5 12h14"/></>}
          </svg>
        </span>
      </button>
      {open && <div className="faq-a">{a}</div>}
    </div>
  );
}

export default function FAQ() {
  return (
    <section id="faq" className="faq-section">
      <div className="container">
        <div className="faq-layout">
          <div className="faq-left">
            <h2 className="faq-heading">Have a <span className="text-teal">question?</span></h2>
            <p className="faq-sub">We're happy to chat—find quick answers here, or get in touch if you need more detail.</p>
            <a href="https://dashboard.blogy.in/signup" className="btn-primary faq-cta" target="_blank" rel="noopener noreferrer">
              Get Started Free
            </a>
          </div>
          <div className="faq-right">
            {FAQS.map((f, i) => <FAQItem key={i} q={f.q} a={f.a} />)}
          </div>
        </div>
      </div>
    </section>
  );
}
